name:                exchangerates
version:             0.0.0.0
github:              "NorfairKing/exchangerates"
license:             BSD3
author:              "Tom Sydney Kerckhove"
maintainer:          "syd.kerckhove@gmail.com"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md

synopsis:            A Haskell client for https://exchangeratesapi.io/
category:            API

description:         Please see the README on Github at <https://github.com/NorfairKing/exchangerates#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- directory
- http-api-data
- http-client
- http-client-tls
- mtl
- servant
- servant-client
- stm
- text
- time
- validity >=0.4.0.3
- validity-containers
- validity-time
- yaml

library:
  source-dirs: src
  exposed-modules:
    - ExchangeRates
    - ExchangeRates.Types
    - ExchangeRates.API
    - ExchangeRates.Client
    - ExchangeRates.Cache

tests:
  exchangerates-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base >=4.9 && <=5
    - exchangerates
    - genvalidity >=0.4.0.4
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
