name:                fixer
version:             0.0.0.0
github:              "NorfairKing/fixer"
license:             BSD3
author:              "Tom Sydney Kerckhove"
maintainer:          "syd.kerckhove@gmail.com"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A Haskell client for http://fixer.io/
category:            API

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/NorfairKing/fixer#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- http-api-data
- http-client
- mtl
- servant
- servant-client
- text
- time
- validity
- validity-containers
- validity-time
- yaml

library:
  source-dirs: src
  exposed-modules:
    - Fixer
    - Fixer.Types
    - Fixer.API
    - Fixer.Client
    - Fixer.Cache

executables:
  fixer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fixer

tests:
  fixer-test:
    main: Spec.hs
    source-dirs: test/
    default-extensions:
    - NoImplicitPrelude
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base >=4.9 && <=5
    - fixer
    - genvalidity-containers
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-text
    - genvalidity-time
    - hspec
